DROP TABLE IF EXISTS a;
drop database if exists d;
DROP DICTIONARY dict;
DROP VIEW v;
TRUNCATE TABLE a;
ALTER TABLE a DELETE WHERE id = 1;
ALTER TABLE a UPDATE v = 'x' WHERE id = 1;
ALTER TABLE a ADD COLUMN c String, DROP COLUMN v;
DELETE FROM a WHERE id = 1;
-- not destructive:
SELECT 'DROP TABLE a; TRUNCATE a';
/* DROP DATABASE d; */ SELECT 1;
SELECT `DROP TABLE a` FROM t;
ALTER TABLE a MODIFY TTL d + INTERVAL 1 DAY DELETE;
