name: publish
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: Publish distribution 📦 to PyPI
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          # setuptools-scm derives the package version from the release tag
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Setup
        run: make setup

      - name: Build
        run: make build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
